version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      kotlin-and-compose:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.compose*"
      ktor:
        patterns:
          - "io.ktor*"
    ignore:
      - dependency-name: "com.android.*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
